from django.db import models

# Create your models here.


def user_directory_path(instance, filename):

    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'property/{0}/hall/{1}'.format(instance.propertyname, filename)


class Contact(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    mobileno = models.CharField(max_length=122)


class Property(models.Model):
    propertyarea = models.CharField(max_length=122)
    propertyname = models.CharField(max_length=122)
    propertytype = models.CharField(max_length=122)
    totalunits = models.CharField(max_length=122)
    availaleunits = models.CharField(max_length=122)
    propertylocation = models.CharField(max_length=122)
    price = models.CharField(max_length=122)
    Status = models.CharField(max_length=122)
    buildername = models.CharField(max_length=122)
    propertydescription = models.CharField(max_length=122)
    propertyvideo = models.CharField(max_length=122)
    propertycondition = models.CharField(max_length=122)
    yearbuilt = models.CharField(max_length=122)
    petfriendly = models.CharField(max_length=122)
    furnished = models.CharField(max_length=122)
    cooling = models.CharField(max_length=122)
    playground = models.CharField(max_length=122)
    parking = models.CharField(max_length=122)
    cctv = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    mobileno = models.CharField(max_length=122)
    propertyaddress = models.CharField(max_length=122)
    builderaddress = models.CharField(max_length=122)
    swimmingpool = models.CharField(max_length=122)
    thumbnail  = models.ImageField(upload_to="property/room")
    image1  = models.ImageField(upload_to="property/room")
    image1  = models.ImageField(upload_to="property/room")
    image2 = models.ImageField(upload_to="property/room")
    image3  = models.ImageField(upload_to="property/bathroom")
    image4 = models.ImageField(upload_to="property/bathroom")
    image5 = models.ImageField(upload_to="property/design")
    image6  = models.ImageField(upload_to="property/kitchen")
    image7 = models.ImageField(upload_to="property/room")
    image8  = models.ImageField(upload_to="property/bathroom")
    image9 = models.ImageField(upload_to="property/design")



class Propertydata(models.Model):
    propertyarea = models.CharField(max_length=122)
    propertyname = models.CharField(max_length=122)
    propertytype = models.CharField(max_length=122)
    totalunits = models.CharField(max_length=122)
    availaleunits = models.CharField(max_length=122)
    propertylocation = models.CharField(max_length=122)
    price = models.CharField(max_length=122)
    Status = models.CharField(max_length=122)
    buildername = models.CharField(max_length=122)
    propertydescription = models.CharField(max_length=122)
    propertyvideo = models.CharField(max_length=122)
    propertycondition = models.CharField(max_length=122)
    yearbuilt = models.CharField(max_length=122)
    petfriendly = models.CharField(max_length=122)
    furnished = models.CharField(max_length=122)
    cooling = models.CharField(max_length=122)
    swimmingpool = models.CharField(max_length=122)
    thumbnail  = models.ImageField(upload_to="property/room")
    image1  = models.ImageField(upload_to="property/room")
    image1  = models.ImageField(upload_to="property/room")
    image2 = models.ImageField(upload_to="property/room")
    image3  = models.ImageField(upload_to="property/bathroom")
    image4 = models.ImageField(upload_to="property/bathroom")
    image5 = models.ImageField(upload_to="property/design")
    image6  = models.ImageField(upload_to="property/kitchen")
    image7 = models.ImageField(upload_to="property/room")
    image8  = models.ImageField(upload_to="property/bathroom")
    image9 = models.ImageField(upload_to="property/design")
     
class Propertydetaile(models.Model):
    propertyarea = models.CharField(max_length=122)
    propertyname = models.CharField(max_length=122)
    propertytype = models.CharField(max_length=122)
    totalunits = models.CharField(max_length=122)
    availaleunits = models.CharField(max_length=122)
    state = models.CharField(max_length=122)
    district = models.CharField(max_length=122)
    pincode = models.CharField(max_length=122)
    price = models.CharField(max_length=122)
    status = models.CharField(max_length=122)
    possassionate=models.CharField(max_length=122)
    buildername = models.CharField(max_length=122)
    propertydescription = models.CharField(max_length=122)
    propertyvideo = models.CharField(max_length=122)
    propertycondition = models.CharField(max_length=122)
    yearbuilt = models.CharField(max_length=122)
    furnished = models.CharField(max_length=122)
    cooling = models.CharField(max_length=122)
    playground = models.CharField(max_length=122)
    parking = models.CharField(max_length=122)
    cctv = models.CharField(max_length=122)
    electricity = models.CharField(max_length=122)
    ac = models.CharField(max_length=122)
    modularkitchen = models.CharField(max_length=122)
    watersupply = models.CharField(max_length=122)
    lpgpipesupply = models.CharField(max_length=122)
    garbagedisposable = models.CharField(max_length=122)
    wifi = models.CharField(max_length=122)
    clubhouse = models.CharField(max_length=122)
    gym = models.CharField(max_length=122)
    sketingground = models.CharField(max_length=122)
    joggingtrack = models.CharField(max_length=122)
    kidsplayarea = models.CharField(max_length=122)
    powerbackup = models.CharField(max_length=122)
    visitingparking = models.CharField(max_length=122)
    guiestsuites = models.CharField(max_length=122)
    accesscardentry = models.CharField(max_length=122)
    railwaystation = models.CharField(max_length=122)
    metro = models.CharField(max_length=122)
    busstation = models.CharField(max_length=122)
    temple = models.CharField(max_length=122)
    highways = models.CharField(max_length=122)
    hospitals = models.CharField(max_length=122)
    mall = models.CharField(max_length=122)
    school = models.CharField(max_length=122)
    college = models.CharField(max_length=122)
    nurshinghome = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    mobileno = models.CharField(max_length=122)
    propertyaddress = models.CharField(max_length=122)
    builderaddress = models.CharField(max_length=122)
    swimmingpool = models.CharField(max_length=122)
    thumbnail  = models.ImageField(upload_to="property")
    image1  = models.ImageField(upload_to="property")
    image2 = models.ImageField(upload_to="property")
    image3  = models.ImageField(upload_to="property")
    image4 = models.ImageField(upload_to="property")




class Interiordesign(models.Model):
    Designer_id = models.CharField(max_length=122)
    Designer_name = models.CharField(max_length=122)
    About_Designer = models.CharField(max_length=122)
    Expreance = models.CharField(max_length=122)
    Project_completed = models.CharField(max_length=122)
    propertyarea = models.CharField(max_length=122)
    Award = models.CharField(max_length=122)
    Livingroom = models.ImageField(upload_to=user_directory_path)
    Kitchen = models.ImageField(upload_to="property/kitchen")
    Master_bedroom = models.ImageField(upload_to="property/room")
    Guest_bedroom = models.ImageField(upload_to="property/bathroom")
    Balconies = models.ImageField(upload_to="property/design")
    Bathroom = models.ImageField(upload_to="property/design")
    Miscellaneous = models.ImageField(upload_to="property/design")
