# Generated by Django 3.0 on 2020-12-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Designer Name')),
                ('aboutyourself', models.CharField(max_length=500, verbose_name='About Designer')),
                ('experience', models.IntegerField(verbose_name='Experience (In Years)')),
                ('projects', models.IntegerField(verbose_name='No of Projects Completed')),
                ('display_projects', models.IntegerField(verbose_name='No of Projects for display?')),
                ('clients', models.IntegerField(verbose_name='No of Satisfied Clients')),
                ('awards', models.IntegerField(verbose_name='No of Awards Won')),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=None, max_length=100, null=True, verbose_name='Unique id')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('city_name', models.CharField(choices=[('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD'), ('AHMEDABAD', 'AHMEDABAD'), ('CHENNAI', 'CHENNAI'), ('KOLKATA', 'KOLKATA'), ('SURAT', 'SURAT'), ('PUNE', 'PUNE'), ('JAIPUR', 'JAIPUR'), ('LUCKNOW', 'LUCKNOW'), ('KANPUR', 'KANPUR'), ('NAGPUR', 'NAGPUR'), ('INDORE', 'INDORE'), ('THANE', 'THANE'), ('BHOPAL', 'BHOPAL'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('CHINCHWAD', 'CHINCHWAD'), ('PATNA', 'PATNA'), ('VADODARA', 'VADODARA'), ('GHAZIABAD', 'GHAZIABAD'), ('LUDHIANA', 'LUDHIANA'), ('AGRA', 'AGRA'), ('NASHIK', 'NASHIK'), ('RANCHI', 'RANCHI'), ('FARIDABAD', 'FARIDABAD'), ('MEERUT', 'MEERUT'), ('RAJKOT', 'RAJKOT'), ('DOMBIVLI', 'DOMBIVLI'), ('VIRAR', 'VIRAR'), ('VARANASI', 'VARANASI'), ('SRINAGAR', 'SRINAGAR'), ('AURANGABAD', 'AURANGABAD'), ('DHANBAD', 'DHANBAD'), ('AMRITSAR', 'AMRITSAR'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('ALLAHABAD', 'ALLAHABAD'), ('HOWRAH', 'HOWRAH'), ('GWALIOR', 'GWALIOR'), ('JABALPUR', 'JABALPUR'), ('COIMBATORE', 'COIMBATORE'), ('VIJAYAWADA', 'VIJAYAWADA'), ('JODHPUR', 'JODHPUR'), ('MADURAI', 'MADURAI'), ('RAIPUR', 'RAIPUR'), ('KOTA', 'KOTA'), ('CHANDIGARH', 'CHANDIGARH'), ('GUWAHATI', 'GUWAHATI'), ('SOLAPUR', 'SOLAPUR'), ('MYSORE', 'MYSORE'), ('BHUBANESWAR', 'BHUBANESWAR'), ('THIRUVANATHAPURAM', 'THIRUVANATHAPURAM'), ('DEHRADUN', 'DEHRADUN'), ('JAMMU', 'JAMMU'), ('AGARTALA', 'AGARTALA'), ('KURNOOL', 'KURNOOL'), ('AIZAWL', 'AIZAWL'), ('IMPHAL', 'IMPHAL'), ('PONDICHERRY', 'PONDICHERRY'), ('GANDHINAGAR', 'GANDHINAGAR'), ('SHIMLA', 'SHIMLA'), ('HOSUR', 'HOSUR'), ('AMARAVATI', 'AMARAVATI'), ('GANGTOK', 'GANGTOK'), ('KOTTAYAM', 'KOTTAYAM')], max_length=200, verbose_name='City Name')),
                ('type_of_property', models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6+ BHK', '6+ BHK'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE')], max_length=200, verbose_name='Type of Property')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/')),
                ('image_1', models.ImageField(upload_to='images/image_1/')),
                ('image_2', models.ImageField(upload_to='images/image_2/')),
                ('image_3', models.ImageField(upload_to='images/image_3/')),
                ('image_4', models.ImageField(upload_to='images/image_4/')),
                ('image_5', models.ImageField(upload_to='images/image_5/')),
                ('timecreated', models.CharField(default='1608625467', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.BooleanField(default=None, null=True, verbose_name='Modular Kitchen')),
                ('livingroom', models.BooleanField(default=None, null=True, verbose_name='Living Room')),
                ('bathroom', models.BooleanField(default=None, null=True, verbose_name='Bath Room')),
                ('bedroom', models.BooleanField(default=None, null=True, verbose_name='Bed Room')),
                ('wardrobe', models.BooleanField(default=None, null=True, verbose_name='Modular Wardrobe')),
            ],
        ),
    ]
