# Generated by Django 3.0 on 2020-12-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='interior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='interiors.Interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='interior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='interiors.Interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='interior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='interiors.Interior'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608625885', max_length=200),
        ),
    ]
