# Generated by Django 3.0 on 2020-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0004_auto_20201222_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('location', models.CharField(max_length=200, verbose_name='Client Name')),
                ('city', models.CharField(max_length=200, verbose_name='Client Name')),
                ('project_date', models.CharField(max_length=200, verbose_name='Client Name')),
                ('type_of_property', models.CharField(max_length=200, verbose_name='Client Name')),
                ('video', models.URLField(blank=True, verbose_name='House Interiors Video')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/')),
                ('image_1', models.ImageField(upload_to='images/image_1/')),
                ('image_2', models.ImageField(upload_to='images/image_2/')),
                ('image_3', models.ImageField(upload_to='images/image_3/')),
                ('image_4', models.ImageField(upload_to='images/image_4/')),
                ('image_5', models.ImageField(upload_to='images/image_5/')),
                ('feedback', models.CharField(max_length=200, verbose_name='Client Name')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608629212', max_length=200),
        ),
    ]
