# Generated by Django 3.0 on 2020-12-26 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0006_auto_20201222_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='budget',
            field=models.IntegerField(default=1, verbose_name='Budget (in Lakhs)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 1, 17, 7, 914805), verbose_name='Project Date'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='designer_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Designer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Duration of Project(in Months)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='Ilsyuu', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(choices=[('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('FULL HOME DESIGN', 'FULL HOME DESIGN'), ('RENOVATION FULL HOME', 'RENOVATION FULL HOME'), ('RENOVATION KITCHEN', 'RENOVATION KITCHEN'), ('RENOVATION LIVING ROOM', 'RENOVATION LIVING ROOM'), ('FURNITURE', 'FURNITURE')], default=1, max_length=200, verbose_name='PropertyplusDecor Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.URLField(blank=True, verbose_name='Complete Project Video Youtube Url'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608945427', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type_of_property',
            field=models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6+ BHK', '6+ BHK'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('VILLA', 'VILLA'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
    ]
