# Generated by Django 3.0 on 2020-12-26 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0010_auto_20201226_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Consultaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email_id', models.CharField(max_length=200, verbose_name='Email id')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone No')),
                ('OTP', models.CharField(max_length=200, verbose_name='Verify - Enter OTP')),
                ('property_name', models.CharField(max_length=200, verbose_name='Property Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_property', models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6+ BHK', '6+ BHK'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE')], max_length=200, verbose_name='Property Type')),
            ],
        ),
        migrations.AddField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNrEZzGe', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 2, 22, 4, 643038), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='PORTXKShfF', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608949324', max_length=200),
        ),
    ]
