# Generated by Django 3.0 on 2020-12-26 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0011_auto_20201226_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_consultation',
            name='budget',
            field=models.IntegerField(default=1, verbose_name='Budget(in Lakhs)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_consultation',
            name='communication',
            field=models.CharField(choices=[('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('TAMIL', 'TAMIL'), ('KANNADA', 'KANNADA'), ('BENGALI', 'BENGALI'), ('GUJRATI', 'GUJRATI')], default=1, max_length=200, verbose_name='Language of Communication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_consultation',
            name='possession',
            field=models.CharField(choices=[('IMMEDIATE', 'IMMEDIATE'), ('1-3 MONTHS', '1-3 MONTHS'), ('4-6 MONTHS', '4-6 MONTHS'), ('HAVE POSSESSION-RENOVATION', 'HAVE POSSESSION-RENOVATION')], default=1, max_length=200, verbose_name='Possession of Home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_consultation',
            name='size_home',
            field=models.CharField(default=1, max_length=200, verbose_name='Area Home(in sqft.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNpvOGYt', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 2, 38, 39, 50450), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='PORTl1KseW', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608950319', max_length=200),
        ),
    ]
