# Generated by Django 3.0 on 2020-12-26 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0014_auto_20201226_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='designer_id',
            field=models.CharField(default='DEZINERzvVdPA', max_length=200, verbose_name='Designer id'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 7, 25, 22, 83537), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNMX93Cj', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='online_consultation',
            name='OTP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Verify-Enter OTP'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 7, 25, 22, 80746), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='PORTCuP3qf', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608967522', max_length=200),
        ),
    ]
