# Generated by Django 3.0 on 2020-12-26 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0015_auto_20201226_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='designer_id',
            field=models.CharField(default='DEZINERlhFXfv', max_length=200, verbose_name='Designer id'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 7, 25, 32, 91937), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNPNEQUk', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 7, 25, 32, 89065), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='PORTrLtVcr', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608967532', max_length=200),
        ),
    ]
