# Generated by Django 3.0 on 2020-12-26 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0016_auto_20201226_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='design_image',
            field=models.ImageField(default=1, upload_to='images/image_1/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='designer_id',
            field=models.CharField(default='DEZINER24YadV', max_length=200, verbose_name='Designer id'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 8, 41, 41, 294642), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESN0OPwtY', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 8, 41, 41, 291745), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(default='PORTCnosOS', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='timecreated',
            field=models.CharField(default='1608972101', max_length=200),
        ),
    ]
