# Generated by Django 3.0 on 2021-01-18 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0018_auto_20210117_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(default='PORTZr9cPU', max_length=200, unique=True)),
                ('client_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('city_name', models.CharField(choices=[('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD'), ('AHMEDABAD', 'AHMEDABAD'), ('CHENNAI', 'CHENNAI'), ('KOLKATA', 'KOLKATA'), ('SURAT', 'SURAT'), ('PUNE', 'PUNE'), ('JAIPUR', 'JAIPUR'), ('LUCKNOW', 'LUCKNOW'), ('KANPUR', 'KANPUR'), ('NAGPUR', 'NAGPUR'), ('INDORE', 'INDORE'), ('THANE', 'THANE'), ('BHOPAL', 'BHOPAL'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('CHINCHWAD', 'CHINCHWAD'), ('PATNA', 'PATNA'), ('VADODARA', 'VADODARA'), ('GHAZIABAD', 'GHAZIABAD'), ('LUDHIANA', 'LUDHIANA'), ('AGRA', 'AGRA'), ('NASHIK', 'NASHIK'), ('RANCHI', 'RANCHI'), ('FARIDABAD', 'FARIDABAD'), ('MEERUT', 'MEERUT'), ('RAJKOT', 'RAJKOT'), ('DOMBIVLI', 'DOMBIVLI'), ('VIRAR', 'VIRAR'), ('VARANASI', 'VARANASI'), ('SRINAGAR', 'SRINAGAR'), ('AURANGABAD', 'AURANGABAD'), ('DHANBAD', 'DHANBAD'), ('AMRITSAR', 'AMRITSAR'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('ALLAHABAD', 'ALLAHABAD'), ('HOWRAH', 'HOWRAH'), ('GWALIOR', 'GWALIOR'), ('JABALPUR', 'JABALPUR'), ('COIMBATORE', 'COIMBATORE'), ('VIJAYAWADA', 'VIJAYAWADA'), ('JODHPUR', 'JODHPUR'), ('MADURAI', 'MADURAI'), ('RAIPUR', 'RAIPUR'), ('KOTA', 'KOTA'), ('CHANDIGARH', 'CHANDIGARH'), ('GUWAHATI', 'GUWAHATI'), ('SOLAPUR', 'SOLAPUR'), ('MYSORE', 'MYSORE'), ('BHUBANESWAR', 'BHUBANESWAR'), ('THIRUVANATHAPURAM', 'THIRUVANATHAPURAM'), ('DEHRADUN', 'DEHRADUN'), ('JAMMU', 'JAMMU'), ('AGARTALA', 'AGARTALA'), ('KURNOOL', 'KURNOOL'), ('AIZAWL', 'AIZAWL'), ('IMPHAL', 'IMPHAL'), ('PONDICHERRY', 'PONDICHERRY'), ('GANDHINAGAR', 'GANDHINAGAR'), ('SHIMLA', 'SHIMLA'), ('HOSUR', 'HOSUR'), ('AMARAVATI', 'AMARAVATI'), ('GANGTOK', 'GANGTOK'), ('KOTTAYAM', 'KOTTAYAM')], max_length=200, verbose_name='City Name')),
                ('type_of_property', models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6+ BHK', '6+ BHK'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE')], max_length=200, verbose_name='Property Type')),
                ('service_type', models.CharField(choices=[('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('FULL HOME DESIGN', 'FULL HOME DESIGN'), ('RENOVATION FULL HOME', 'RENOVATION FULL HOME'), ('RENOVATION KITCHEN', 'RENOVATION KITCHEN'), ('RENOVATION LIVING ROOM', 'RENOVATION LIVING ROOM'), ('FURNITURE', 'FURNITURE')], max_length=200, verbose_name='PropertyplusDecor Service')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 18, 3, 2, 21, 111304), verbose_name='Project Date')),
                ('duration', models.IntegerField(verbose_name='Duration of Project(in Months)')),
                ('budget', models.IntegerField(verbose_name='Budget (in Lakhs)')),
                ('designer_name', models.CharField(max_length=200, verbose_name='Designer Name')),
                ('video', models.URLField(blank=True, verbose_name='Complete Project Video Youtube Url')),
                ('timecreated', models.CharField(default='1610938941', max_length=200)),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfoliobasic', to='interiors.Interior')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/')),
                ('image_1', models.ImageField(upload_to='images/image_1/')),
                ('image_2', models.ImageField(upload_to='images/image_2/')),
                ('image_3', models.ImageField(upload_to='images/image_3/')),
                ('image_4', models.ImageField(upload_to='images/image_4/')),
                ('image_5', models.ImageField(upload_to='images/image_5/')),
                ('timecreated', models.CharField(default='1610938941', max_length=200)),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfoliogallery', to='interiors.Interior')),
            ],
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='designer_id',
            field=models.CharField(default='DEZINERAu0KOa', max_length=200, verbose_name='Designer id'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 3, 2, 21, 114492), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNDP84jd', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
