# Generated by Django 3.0 on 2021-01-18 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0019_auto_20210118_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioGalleryLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(max_length=200, verbose_name='Portfolio Id')),
                ('thumbnail', models.URLField()),
                ('image_1', models.URLField()),
                ('image_2', models.URLField()),
                ('image_3', models.URLField()),
                ('image_4', models.URLField()),
                ('image_5', models.URLField()),
                ('timecreated', models.CharField(default='1610942698', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='interior',
        ),
        migrations.AddField(
            model_name='portfoliogallery',
            name='portfolio_id',
            field=models.CharField(default='PORTJvCjyM', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='designer_id',
            field=models.CharField(default='DEZINERTh2kqP', max_length=200, verbose_name='Designer id'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 4, 4, 58, 987242), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNsFR2Zj', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 4, 4, 58, 983531), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='portfolio_id',
            field=models.CharField(max_length=200, verbose_name='Portfolio Id'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1610942698', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1610942698', max_length=200),
        ),
    ]
