# Generated by Django 3.0 on 2021-01-18 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0023_auto_20210118_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 9, 30, 6, 17512), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='service_type',
            field=models.CharField(choices=[('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('COMPLETE HOME DESIGN', 'COMPLETE HOME DESIGN'), ('RENOVATION COMPLETE HOME', 'RENOVATION COMPLETE HOME'), ('RENOVATION KITCHEN', 'RENOVATION KITCHEN'), ('ESSENTIAL FURNITURES', 'ESSENTIAL FURNITURES')], max_length=200, verbose_name='PropertyplusDecor Service'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT (1 BHK)', 'APARTMENT (1 BHK)'), ('APARTMENT (2 BHK)', 'APARTMENT (2 BHK)'), ('APARTMENT (3 BHK)', 'APARTMENT (3 BHK)'), ('APARTMENT (4 BHK)', 'APARTMENT (4 BHK)'), ('APARTMENT (5 BHK)', 'APARTMENT (5 BHK)'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNk6CImJ', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='service_type',
            field=models.CharField(choices=[('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('COMPLETE HOME DESIGN', 'COMPLETE HOME DESIGN'), ('RENOVATION COMPLETE HOME', 'RENOVATION COMPLETE HOME'), ('RENOVATION KITCHEN', 'RENOVATION KITCHEN'), ('ESSENTIAL FURNITURES', 'ESSENTIAL FURNITURES')], max_length=200, verbose_name='PropertyplusDecor Service'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1610962206', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT (1 BHK)', 'APARTMENT (1 BHK)'), ('APARTMENT (2 BHK)', 'APARTMENT (2 BHK)'), ('APARTMENT (3 BHK)', 'APARTMENT (3 BHK)'), ('APARTMENT (4 BHK)', 'APARTMENT (4 BHK)'), ('APARTMENT (5 BHK)', 'APARTMENT (5 BHK)'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1610962206', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1610962206', max_length=200),
        ),
        migrations.AlterField(
            model_name='pre_consultation',
            name='service_type',
            field=models.CharField(choices=[('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('COMPLETE HOME DESIGN', 'COMPLETE HOME DESIGN'), ('RENOVATION COMPLETE HOME', 'RENOVATION COMPLETE HOME'), ('RENOVATION KITCHEN', 'RENOVATION KITCHEN'), ('ESSENTIAL FURNITURES', 'ESSENTIAL FURNITURES')], max_length=200, verbose_name='PropertyplusDecor Service'),
        ),
        migrations.AlterField(
            model_name='pre_consultation',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT (1 BHK)', 'APARTMENT (1 BHK)'), ('APARTMENT (2 BHK)', 'APARTMENT (2 BHK)'), ('APARTMENT (3 BHK)', 'APARTMENT (3 BHK)'), ('APARTMENT (4 BHK)', 'APARTMENT (4 BHK)'), ('APARTMENT (5 BHK)', 'APARTMENT (5 BHK)'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
    ]
