# Generated by Django 3.0 on 2021-01-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0024_auto_20210118_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 10, 13, 5, 958404), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT_1BHK', 'APARTMENT_1BHK'), ('APARTMENT_2BHK', 'APARTMENT_2BHK'), ('APARTMENT_3BHK', 'APARTMENT_3BHK'), ('APARTMENT_4BHK', 'APARTMENT_4BHK'), ('APARTMENT_5BHK', 'APARTMENT_5BHK'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNJb9kTv', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1610964785', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT_1BHK', 'APARTMENT_1BHK'), ('APARTMENT_2BHK', 'APARTMENT_2BHK'), ('APARTMENT_3BHK', 'APARTMENT_3BHK'), ('APARTMENT_4BHK', 'APARTMENT_4BHK'), ('APARTMENT_5BHK', 'APARTMENT_5BHK'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1610964785', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1610964785', max_length=200),
        ),
        migrations.AlterField(
            model_name='pre_consultation',
            name='type_of_property',
            field=models.CharField(choices=[('APARTMENT_1BHK', 'APARTMENT_1BHK'), ('APARTMENT_2BHK', 'APARTMENT_2BHK'), ('APARTMENT_3BHK', 'APARTMENT_3BHK'), ('APARTMENT_4BHK', 'APARTMENT_4BHK'), ('APARTMENT_5BHK', 'APARTMENT_5BHK'), ('VILLA', 'VILLA'), ('INDEPENDENT HOUSE', 'INDEPENDENT HOUSE'), ('COMMERCIAL', 'COMMERCIAL')], max_length=200, verbose_name='Property Type'),
        ),
    ]
