# Generated by Django 3.0 on 2021-01-20 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0025_auto_20210118_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 45, 35, 894892), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNlY0CmU', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_type',
            field=models.CharField(choices=[('LIVING ROOM', 'LIVING ROOM'), ('MODULAR KITCHEN', 'MODULAR KITCHEN'), ('BATHROOM', 'BATHROOM'), ('BED ROOM', 'BED ROOM'), ('KIDS ROOM', 'KIDS ROOM')], max_length=200, verbose_name='Design Type'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611135935', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611135935', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611135935', max_length=200),
        ),
    ]
