# Generated by Django 3.0 on 2021-01-20 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0028_auto_20210120_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliobasic',
            name='aboutyourself',
        ),
        migrations.RemoveField(
            model_name='portfoliobasic',
            name='experience',
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 10, 11, 28, 507955), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(default='DESNIp4DDn', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611137488', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611137488', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611137488', max_length=200),
        ),
    ]
