# Generated by Django 3.0 on 2021-01-20 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0029_auto_20210120_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='designer_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Designer Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 10, 58, 1, 979295), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_id',
            field=models.CharField(max_length=200, verbose_name='Design Id'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611140281', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611140281', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611140281', max_length=200),
        ),
    ]
