# Generated by Django 3.0 on 2021-01-20 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0031_auto_20210120_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='designs',
            name='summary',
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 11, 4, 21, 369106), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611140661', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611140661', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611140661', max_length=200),
        ),
    ]
