# Generated by Django 3.0 on 2021-01-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0037_auto_20210122_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliobasic',
            name='image_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobasic',
            name='image_2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobasic',
            name='image_3',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobasic',
            name='image_4',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobasic',
            name='image_5',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliobasic',
            name='thumbnail',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 15, 46, 55, 375739), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='designgallery',
            name='designer_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Designer Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611416815', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611416815', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611416815', max_length=200),
        ),
    ]
