# Generated by Django 3.0 on 2021-01-25 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0039_auto_20210123_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='designgallery',
            name='designer_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Designer Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 12, 51, 4, 169074), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611579064', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611579064', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611579064', max_length=200),
        ),
    ]
