# Generated by Django 3.0 on 2021-01-26 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0041_auto_20210125_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliobasic',
            name='aboutyourself',
            field=models.CharField(default=1, max_length=500, verbose_name='About Designer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 7, 46, 29, 526642), verbose_name='Project Date'),
        ),
        migrations.AlterField(
            model_name='portfoliobasic',
            name='timecreated',
            field=models.CharField(default='1611647189', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='timecreated',
            field=models.CharField(default='1611647189', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliogallerylinks',
            name='timecreated',
            field=models.CharField(default='1611647189', max_length=200),
        ),
    ]
