# Generated by Django 3.0 on 2020-08-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_description', models.CharField(default=None, max_length=100, null=True, verbose_name='Property Description')),
                ('property_name', models.CharField(default=None, max_length=100, null=True, verbose_name='Property Name')),
                ('property_status', models.CharField(choices=[('FOR SALE', 'For Sale'), ('LEASED', 'Leased'), ('SOLD', 'Sold'), ('SPECIAL OFFER', 'Special Offer'), ('NEW ADDITION', 'New Addition'), ('RENTAL', 'Rental'), ('REDUCED', 'Reduced')], max_length=20, verbose_name='Property Status')),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('CONDO', 'Condo'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='Property Type')),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property Price')),
                ('property_space', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property Space(Sqft)')),
                ('property_video', models.URLField(blank=True, verbose_name='Property Video')),
            ],
        ),
        migrations.CreateModel(
            name='List_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_thumbnail', models.ImageField(blank=True, upload_to='property_thumbnail')),
                ('property_gallery', models.ImageField(blank=True, upload_to='property_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='List_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default=None, max_length=100, null=True, verbose_name='Property Location')),
                ('State', models.CharField(choices=[('KARNATAKA', 'Karnataka')], max_length=20, verbose_name='Property Status')),
                ('City', models.CharField(choices=[('BANGALORE', 'Bangalore')], max_length=20, verbose_name='Property Status')),
                ('Longitude', models.CharField(default=None, max_length=100, null=True, verbose_name='Longitude')),
                ('Latitude', models.CharField(default=None, max_length=100, null=True, verbose_name='Latitude')),
            ],
        ),
    ]
