# Generated by Django 3.0 on 2020-08-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_Basic',
            new_name='Basic_Information',
        ),
        migrations.RenameModel(
            old_name='List_Features',
            new_name='Details',
        ),
        migrations.RenameModel(
            old_name='List_Details',
            new_name='Features',
        ),
        migrations.RenameModel(
            old_name='List_Gallery',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='List_Location',
            new_name='Location',
        ),
    ]
