# Generated by Django 3.0 on 2020-08-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200829_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='property_description',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Property Description'),
        ),
    ]
