# Generated by Django 3.0 on 2020-08-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200829_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='City',
            field=models.CharField(choices=[('BANGALORE', 'Bangalore')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.CharField(choices=[('KARNATAKA', 'Karnataka')], max_length=20, verbose_name='State'),
        ),
    ]
