# Generated by Django 3.0 on 2020-08-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20200829_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='property_id',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Property Id'),
        ),
    ]
