# Generated by Django 3.0 on 2020-08-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200831_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_friendly', models.BooleanField(default=None, verbose_name='Pet Friendly')),
                ('furnished', models.BooleanField(default=None, verbose_name='Furnished')),
                ('cooling', models.BooleanField(default=None, verbose_name='Cooling')),
                ('parking', models.BooleanField(default=None, verbose_name='Parking')),
                ('mailbox', models.BooleanField(default=None, verbose_name='Mailbox')),
                ('city_view', models.BooleanField(default=None, verbose_name='City View')),
            ],
        ),
    ]
