# Generated by Django 3.0 on 2020-08-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Information', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Basic_Information')),
                ('Details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Details')),
                ('Features', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Features')),
                ('Gallery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Gallery')),
                ('Location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Location')),
            ],
        ),
    ]
