# Generated by Django 3.0 on 2020-08-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_auto_20200831_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Basic_Information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basicinfo', to='listing.Basic_Information'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='listing.Details'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listing.Features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='listing.Gallery'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='listing.Location'),
        ),
    ]
