# Generated by Django 3.0 on 2020-08-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_auto_20200831_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='basic_information',
        ),
        migrations.AddField(
            model_name='property',
            name='basic_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Basic_Information'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='details',
        ),
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Details'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Features'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='gallery',
        ),
        migrations.AddField(
            model_name='property',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Gallery'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Location'),
        ),
    ]
