# Generated by Django 3.0 on 2020-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_auto_20200831_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=None, max_length=100, null=True, verbose_name='Unique id')),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
