# Generated by Django 3.0 on 2020-09-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20200912_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_information',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BasicInformation', to='listing.Listing'),
        ),
        migrations.AddField(
            model_name='details',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HomeDetails', to='listing.Listing'),
        ),
        migrations.AddField(
            model_name='features',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HomeFeatures', to='listing.Listing'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HomeGallery', to='listing.Listing'),
        ),
        migrations.AddField(
            model_name='location',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HomeLocation', to='listing.Listing'),
        ),
    ]
