# Generated by Django 3.0 on 2020-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20200927_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='space',
            field=models.IntegerField(verbose_name='Property Space(Sqft)'),
        ),
    ]
