# Generated by Django 3.0 on 2020-10-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_auto_20200927_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BasicInformation', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='details',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeDetails', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='features',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeFeatures', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeGallery', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='location',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeLocation', to='listing.Listing'),
        ),
    ]
