# Generated by Django 3.0 on 2020-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_auto_20201011_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='property_gallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='property_gallery_1',
            field=models.FileField(blank=True, upload_to='property_gallery_1'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='property_gallery_2',
            field=models.FileField(blank=True, upload_to='property_gallery_2'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='property_gallery_3',
            field=models.FileField(blank=True, upload_to='property_gallery_3'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='property_gallery_4',
            field=models.FileField(blank=True, upload_to='property_gallery_4'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='property_gallery_5',
            field=models.FileField(blank=True, upload_to='property_gallery_5'),
        ),
    ]
