# Generated by Django 3.0 on 2020-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20201013_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='price',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('CONDO', 'Condo'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='Property Price'),
        ),
    ]
