# Generated by Django 3.0 on 2020-10-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_auto_20201013_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Property Price'),
        ),
    ]
