# Generated by Django 3.0 on 2020-10-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_auto_20201013_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Property Description'),
        ),
    ]
