# Generated by Django 3.0 on 2020-10-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_auto_20201013_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BasicInformation', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='details',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeDetails', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='features',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeFeatures', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeGallery', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='location',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeLocation', to='listing.Listing'),
        ),
    ]
