# Generated by Django 3.0 on 2020-10-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0025_auto_20201013_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_information',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='details',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='features',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='location',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='basic_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListingBasicInfo', to='listing.Basic_Information'),
        ),
        migrations.AddField(
            model_name='listing',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListingDetails', to='listing.Details'),
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListingFeatures', to='listing.Features'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListingGallery', to='listing.Gallery'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListingLocation', to='listing.Location'),
        ),
    ]
