# Generated by Django 3.0 on 2020-10-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0027_auto_20201031_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_links',
            name='listing',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='Gallery_links', to='listing.Listing'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604129302', max_length=200),
        ),
    ]
