# Generated by Django 3.0 on 2020-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0028_auto_20201031_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='property_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='property_name',
            field=models.CharField(max_length=200, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604133058', max_length=200),
        ),
    ]
