# Generated by Django 3.0 on 2020-10-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0029_auto_20201031_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_links',
            old_name='timecreated',
            new_name='property_id',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604137508', max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='image_1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='image_2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='image_3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='image_4',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='image_5',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery_links',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
