# Generated by Django 3.0 on 2020-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0032_auto_20201101_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Any_Location', 'Any_Location'), ('BANGALORE', 'Bangalore')], max_length=50, verbose_name='Location')),
                ('status', models.CharField(choices=[('Any Status', 'Any Status'), ('FOR SALE', 'For Sale'), ('UNDERCONSTRUCTION', 'Underconstruction'), ('LEASED', 'Leased'), ('SOLD', 'Sold'), ('SPECIAL OFFER', 'Special Offer'), ('NEW ADDITION', 'New Addition'), ('RENTAL', 'Rental'), ('REDUCED', 'Reduced')], max_length=50, verbose_name='Status')),
                ('price_range', models.CharField(choices=[('Any Price', 'Any Price'), ('< 20 lakhs', '< 20 Lakhs'), ('20 - 40 Lakhs', '20 - 40 Lakhs'), ('40 - 60 Lakhs', '40 - 60 Lakhs'), ('60 - 80 Lakhs', '60 - 80 Lakhs'), ('< 1 Crore', '< 1 Crore'), ('> 1 Crore', '> 1 Crore')], max_length=50, verbose_name='Property Range')),
                ('beds', models.CharField(choices=[('Any', 'Any'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='No of Beds')),
                ('bathrooms', models.CharField(choices=[('Any', 'Any'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='No of Bathrooms')),
                ('prop_type', models.CharField(choices=[('Any Type', 'Any Type'), ('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('CONDO', 'Condo'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=50, verbose_name='Property Type')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604289630', max_length=200),
        ),
    ]
