# Generated by Django 3.0 on 2020-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0033_auto_20201102_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='price_range',
            field=models.CharField(choices=[('Any Price', 'Any Price'), ('< 20 lakhs', '< 20 Lakhs'), ('20 - 40 Lakhs', '20 - 40 Lakhs'), ('40 - 60 Lakhs', '40 - 60 Lakhs'), ('60 - 80 Lakhs', '60 - 80 Lakhs'), ('< 1 Crore', '< 1 Crore'), ('> 1 Crore', '> 1 Crore')], max_length=50, verbose_name='Price Range'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604394997', max_length=200),
        ),
    ]
