# Generated by Django 3.0 on 2020-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0034_auto_20201103_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='bathrooms',
            field=models.CharField(choices=[('Any', 'Any'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='filter_listings',
            name='beds',
            field=models.CharField(choices=[('Any', 'Any'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='Beds'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604395317', max_length=200),
        ),
    ]
