# Generated by Django 3.0 on 2020-11-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0035_auto_20201103_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_listings',
            name='space',
            field=models.CharField(choices=[('Any Size', 'Any Size'), ('< 500 Sqft', '< 500 Sqft'), ('500 - 1000 Sqft', '500 - 1000 Sqft'), ('1000 - 1500 Sqft', '1000 - 1500 Sqft'), ('1500 - 2000 Sqft', '1500 - 2000 Sqft'), ('> 2000 Sqft', '> 2000 Sqft')], default=1, max_length=50, verbose_name='Space'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604395807', max_length=200),
        ),
    ]
