# Generated by Django 3.0 on 2020-11-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0038_auto_20201104_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('BEACH HOUSE', 'Beach House'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='details',
            name='type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('BEACH HOUSE', 'Beach House'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='filter_listings',
            name='prop_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('BEACH HOUSE', 'Beach House'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604498813', max_length=200),
        ),
    ]
