# Generated by Django 3.0 on 2020-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0040_auto_20201107_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604735515', max_length=200),
        ),
    ]
