# Generated by Django 3.0 on 2020-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0041_auto_20201107_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_information',
            name='description',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='price',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='space',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='status',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='type',
        ),
        migrations.RemoveField(
            model_name='basic_information',
            name='video',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604735858', max_length=200),
        ),
    ]
