# Generated by Django 3.0 on 2020-11-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0042_auto_20201107_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('READY TO MOVE', 'READY TO MOVE'), ('UNDERCONSTRUCTION', 'Underconstruction'), ('LEASED', 'Leased'), ('SOLD', 'Sold'), ('SPECIAL OFFER', 'Special Offer'), ('NEW ADDITION', 'New Addition'), ('RENTAL', 'Rental'), ('REDUCED', 'Reduced')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604735949', max_length=200),
        ),
    ]
