# Generated by Django 3.0 on 2020-11-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0045_auto_20201107_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='project_area',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Property Area (In Acres)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604736398', max_length=200),
        ),
    ]
