# Generated by Django 3.0 on 2020-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0049_auto_20201107_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_information',
            old_name='type',
            new_name='type1',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604738364', max_length=200),
        ),
    ]
