# Generated by Django 3.0 on 2020-11-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0052_auto_20201107_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_information',
            old_name='type1',
            new_name='propertytype',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604738745', max_length=200),
        ),
    ]
