# Generated by Django 3.0 on 2020-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0055_auto_20201107_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1604750294', max_length=200),
        ),
    ]
