# Generated by Django 3.0 on 2020-11-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0062_auto_20201110_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1605595674', max_length=200),
        ),
        migrations.CreateModel(
            name='Consolidated_tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_information', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='listing.Basic_Information')),
                ('details', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='listing.Details')),
                ('features', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='listing.Features')),
                ('gallery_links', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='listing.Gallery_links')),
                ('location', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='listing.Location')),
            ],
        ),
    ]
