# Generated by Django 3.0 on 2020-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0063_auto_20201117_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_information',
            name='propertytype',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('PLOTS', 'Plots'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='PropertyType'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1605958272', max_length=200),
        ),
    ]
