# Generated by Django 3.0 on 2020-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0064_auto_20201121_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='builder_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Builder Name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='propertytype',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('PLOTS', 'Plots'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=20, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='filter_listings',
            name='prop_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('APARTMENT', 'Apartment'), ('PLOTS', 'Plots'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex')], max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606030660', max_length=200),
        ),
    ]
