# Generated by Django 3.0 on 2020-11-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0066_auto_20201125_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(verbose_name='Property Price'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606291291', max_length=200),
        ),
    ]
