# Generated by Django 3.0 on 2020-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0068_auto_20201125_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='price_unit',
            field=models.CharField(choices=[('Lakhs', 'Lakhs'), ('Cr', 'Cr')], default=1, max_length=20, verbose_name='Price Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606294075', max_length=200),
        ),
    ]
