# Generated by Django 3.0 on 2020-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0069_auto_20201125_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='details',
            name='price_withunit',
            field=models.CharField(default=1, max_length=20, verbose_name='Display Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606294874', max_length=200),
        ),
    ]
