# Generated by Django 3.0 on 2020-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0070_auto_20201125_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606298345', max_length=200),
        ),
    ]
