# Generated by Django 3.0 on 2020-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0071_auto_20201125_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='amphitheatre',
            field=models.BooleanField(default=None, null=True, verbose_name='Amphitheatre'),
        ),
        migrations.AddField(
            model_name='features',
            name='badminton_court',
            field=models.BooleanField(default=None, null=True, verbose_name='Badminton Court'),
        ),
        migrations.AddField(
            model_name='features',
            name='basketball_court',
            field=models.BooleanField(default=None, null=True, verbose_name='Basketball Court'),
        ),
        migrations.AddField(
            model_name='features',
            name='childs_playarea',
            field=models.BooleanField(default=None, null=True, verbose_name="Child's Play Area"),
        ),
        migrations.AddField(
            model_name='features',
            name='cycling_track',
            field=models.BooleanField(default=None, null=True, verbose_name='Cycling Track'),
        ),
        migrations.AddField(
            model_name='features',
            name='multipurpose_court',
            field=models.BooleanField(default=None, null=True, verbose_name='Multipurpose Court'),
        ),
        migrations.AddField(
            model_name='features',
            name='outdoor_gym',
            field=models.BooleanField(default=None, null=True, verbose_name='Outdoor Gym'),
        ),
        migrations.AddField(
            model_name='features',
            name='snooker_table',
            field=models.BooleanField(default=None, null=True, verbose_name='Snooker Table'),
        ),
        migrations.AddField(
            model_name='features',
            name='squash_court',
            field=models.BooleanField(default=None, null=True, verbose_name='Squash Court'),
        ),
        migrations.AddField(
            model_name='features',
            name='srcitizen_area',
            field=models.BooleanField(default=None, null=True, verbose_name='Sr. Citizen Area'),
        ),
        migrations.AddField(
            model_name='features',
            name='swimming_pool',
            field=models.BooleanField(default=None, null=True, verbose_name='Swimming Pool'),
        ),
        migrations.AddField(
            model_name='features',
            name='yoga_room',
            field=models.BooleanField(default=None, null=True, verbose_name='Yoga Room'),
        ),
        migrations.AlterField(
            model_name='features',
            name='city_view',
            field=models.BooleanField(default=None, null=True, verbose_name='City View'),
        ),
        migrations.AlterField(
            model_name='features',
            name='cooling',
            field=models.BooleanField(default=None, null=True, verbose_name='Cooling'),
        ),
        migrations.AlterField(
            model_name='features',
            name='furnished',
            field=models.BooleanField(default=None, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='features',
            name='mailbox',
            field=models.BooleanField(default=None, null=True, verbose_name='Mailbox'),
        ),
        migrations.AlterField(
            model_name='features',
            name='parking',
            field=models.BooleanField(default=None, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='features',
            name='pet_friendly',
            field=models.BooleanField(default=None, null=True, verbose_name='Pet Friendly'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606300951', max_length=200),
        ),
    ]
