# Generated by Django 3.0 on 2020-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0072_auto_20201125_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606300959', max_length=200),
        ),
    ]
