# Generated by Django 3.0 on 2020-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0073_auto_20201125_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('date', models.CharField(max_length=200, verbose_name='Date & Time')),
                ('comment', models.CharField(max_length=200, verbose_name='Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606306199', max_length=200),
        ),
    ]
