# Generated by Django 3.0 on 2020-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0074_auto_20201125_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='completed_projects',
            field=models.IntegerField(default=1, verbose_name='Completed Projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='ongoing_projects',
            field=models.IntegerField(default=1, verbose_name='Ongoing Projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='sold_projects',
            field=models.IntegerField(default=1, verbose_name='Sold Projects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606316822', max_length=200),
        ),
    ]
