# Generated by Django 3.0 on 2020-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0077_auto_20201126_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_listings',
            name='builder',
            field=models.CharField(default=1, max_length=50, verbose_name='Builder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter_listings',
            name='sort_by',
            field=models.CharField(choices=[('', '')], default=1, max_length=50, verbose_name='Sort By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606396865', max_length=200),
        ),
    ]
