# Generated by Django 3.0 on 2020-11-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0078_auto_20201126_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='sort_by',
            field=models.CharField(choices=[('Price: High to Low', 'Price: High to Low'), ('Price: Low to High', 'Price: Low to High')], max_length=50, verbose_name='Sort By'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606397127', max_length=200),
        ),
    ]
