# Generated by Django 3.0 on 2020-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0079_auto_20201126_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='builder',
            field=models.CharField(choices=[('Price: High to Low', 'Price: High to Low'), ('Price: Low to High', 'Price: Low to High')], max_length=50, verbose_name='Builder'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606399732', max_length=200),
        ),
    ]
