# Generated by Django 3.0 on 2020-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0080_auto_20201126_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='builder',
            field=models.CharField(choices=[('AMSA', 'Amsa'), ('SHOBHA', 'Shobha'), ('SARITA', 'Sarita')], max_length=50, verbose_name='Builder'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606399792', max_length=200),
        ),
    ]
