# Generated by Django 3.0 on 2020-11-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0083_auto_20201127_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606452928', max_length=200),
        ),
    ]
