# Generated by Django 3.0 on 2020-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0084_auto_20201127_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='builder',
            field=models.CharField(choices=[('Amsa', 'Amsa'), ('Shobha', 'Shobha'), ('Sarita', 'Sarita')], max_length=50, verbose_name='Builder'),
        ),
        migrations.AlterField(
            model_name='filter_listings',
            name='prop_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('RESIDENTIAL', 'RESIDENTIAL'), ('APARTMENT', 'APARTMENT'), ('PLOTS', 'PLOTS'), ('VILLA', 'VILLA'), ('DUPLEX', 'DUPLEX')], max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606462562', max_length=200),
        ),
    ]
