# Generated by Django 3.0 on 2020-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0085_auto_20201127_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1606462579', max_length=200),
        ),
    ]
