# Generated by Django 3.0 on 2020-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0088_auto_20201203_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1607578121', max_length=200),
        ),
    ]
