# Generated by Django 3.0 on 2020-12-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0093_auto_20201210_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1607578567', max_length=200),
        ),
    ]
