# Generated by Django 3.0 on 2020-12-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0096_auto_20201217_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608622407', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='City',
            field=models.CharField(choices=[('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD'), ('AHMEDABAD', 'AHMEDABAD'), ('CHENNAI', 'CHENNAI'), ('KOLKATA', 'KOLKATA'), ('SURAT', 'SURAT'), ('PUNE', 'PUNE'), ('JAIPUR', 'JAIPUR'), ('LUCKNOW', 'LUCKNOW'), ('KANPUR', 'KANPUR'), ('NAGPUR', 'NAGPUR'), ('INDORE', 'INDORE'), ('THANE', 'THANE'), ('BHOPAL', 'BHOPAL'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('CHINCHWAD', 'CHINCHWAD'), ('PATNA', 'PATNA'), ('VADODARA', 'VADODARA'), ('GHAZIABAD', 'GHAZIABAD'), ('LUDHIANA', 'LUDHIANA'), ('AGRA', 'AGRA'), ('NASHIK', 'NASHIK'), ('RANCHI', 'RANCHI'), ('FARIDABAD', 'FARIDABAD'), ('MEERUT', 'MEERUT'), ('RAJKOT', 'RAJKOT'), ('DOMBIVLI', 'DOMBIVLI'), ('VIRAR', 'VIRAR'), ('VARANASI', 'VARANASI'), ('SRINAGAR', 'SRINAGAR'), ('AURANGABAD', 'AURANGABAD'), ('DHANBAD', 'DHANBAD'), ('AMRITSAR', 'AMRITSAR'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('ALLAHABAD', 'ALLAHABAD'), ('HOWRAH', 'HOWRAH'), ('GWALIOR', 'GWALIOR'), ('JABALPUR', 'JABALPUR'), ('COIMBATORE', 'COIMBATORE'), ('VIJAYAWADA', 'VIJAYAWADA'), ('JODHPUR', 'JODHPUR'), ('MADURAI', 'MADURAI'), ('RAIPUR', 'RAIPUR'), ('KOTA', 'KOTA'), ('CHANDIGARH', 'CHANDIGARH'), ('GUWAHATI', 'GUWAHATI'), ('SOLAPUR', 'SOLAPUR'), ('MYSORE', 'MYSORE'), ('BHUBANESWAR', 'BHUBANESWAR'), ('THIRUVANATHAPURAM', 'THIRUVANATHAPURAM'), ('DEHRADUN', 'DEHRADUN'), ('JAMMU', 'JAMMU'), ('AGARTALA', 'AGARTALA'), ('KURNOOL', 'KURNOOL'), ('AIZAWL', 'AIZAWL'), ('IMPHAL', 'IMPHAL'), ('PONDICHERRY', 'PONDICHERRY'), ('GANDHINAGAR', 'GANDHINAGAR'), ('SHIMLA', 'SHIMLA'), ('HOSUR', 'HOSUR'), ('AMARAVATI', 'AMARAVATI'), ('GANGTOK', 'GANGTOK'), ('KOTTAYAM', 'KOTTAYAM')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.CharField(choices=[('KARNATAKA', 'KARNATAKA'), ('MAHARASHTRA', 'MAHARASHTRA'), ('DELHI', 'DELHI'), ('TELANGANA', 'TELANGANA'), ('GUJARAT', 'GUJARAT'), ('TAMIL NADU', 'TAMIL NADU'), ('WEST BENGAL', 'WEST BENGAL'), ('RAJASTHAN', 'RAJASTHAN'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('PUNJAB', 'PUNJAB'), ('JHARKHAND', 'JHARKHAND'), ('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('CHHATTISGARH', 'CHHATTISGARH'), ('CHANDIGARH', 'CHANDIGARH'), ('ASSAM', 'ASSAM'), ('ODISHA', 'ODISHA'), ('KERALA', 'KERALA'), ('TRIPURA', 'TRIPURA'), ('MANIPUR', 'MANIPUR'), ('PUDUCHERRY', 'PUDUCHERRY'), ('HIMACHAL PRADESH', 'HIMACHAL PRADESH'), ('SIKKIM', 'SIKKIM')], max_length=20, verbose_name='State'),
        ),
    ]
