# Generated by Django 3.0 on 2020-12-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0097_auto_20201222_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608622717', max_length=200),
        ),
    ]
