# Generated by Django 3.0 on 2020-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0098_auto_20201222_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_listings',
            name='location',
            field=models.CharField(choices=[('Any Location', 'Any Location'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD'), ('AHMEDABAD', 'AHMEDABAD'), ('CHENNAI', 'CHENNAI'), ('KOLKATA', 'KOLKATA'), ('SURAT', 'SURAT'), ('PUNE', 'PUNE'), ('JAIPUR', 'JAIPUR'), ('LUCKNOW', 'LUCKNOW'), ('KANPUR', 'KANPUR'), ('NAGPUR', 'NAGPUR'), ('INDORE', 'INDORE'), ('THANE', 'THANE'), ('BHOPAL', 'BHOPAL'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('CHINCHWAD', 'CHINCHWAD'), ('PATNA', 'PATNA'), ('VADODARA', 'VADODARA'), ('GHAZIABAD', 'GHAZIABAD'), ('LUDHIANA', 'LUDHIANA'), ('AGRA', 'AGRA'), ('NASHIK', 'NASHIK'), ('RANCHI', 'RANCHI'), ('FARIDABAD', 'FARIDABAD'), ('MEERUT', 'MEERUT'), ('RAJKOT', 'RAJKOT'), ('DOMBIVLI', 'DOMBIVLI'), ('VIRAR', 'VIRAR'), ('VARANASI', 'VARANASI'), ('SRINAGAR', 'SRINAGAR'), ('AURANGABAD', 'AURANGABAD'), ('DHANBAD', 'DHANBAD'), ('AMRITSAR', 'AMRITSAR'), ('NAVI MUMBAI', 'NAVI MUMBAI'), ('ALLAHABAD', 'ALLAHABAD'), ('HOWRAH', 'HOWRAH'), ('GWALIOR', 'GWALIOR'), ('JABALPUR', 'JABALPUR'), ('COIMBATORE', 'COIMBATORE'), ('VIJAYAWADA', 'VIJAYAWADA'), ('JODHPUR', 'JODHPUR'), ('MADURAI', 'MADURAI'), ('RAIPUR', 'RAIPUR'), ('KOTA', 'KOTA'), ('CHANDIGARH', 'CHANDIGARH'), ('GUWAHATI', 'GUWAHATI'), ('SOLAPUR', 'SOLAPUR'), ('MYSORE', 'MYSORE'), ('BHUBANESWAR', 'BHUBANESWAR'), ('THIRUVANATHAPURAM', 'THIRUVANATHAPURAM'), ('DEHRADUN', 'DEHRADUN'), ('JAMMU', 'JAMMU'), ('AGARTALA', 'AGARTALA'), ('KURNOOL', 'KURNOOL'), ('AIZAWL', 'AIZAWL'), ('IMPHAL', 'IMPHAL'), ('PONDICHERRY', 'PONDICHERRY'), ('GANDHINAGAR', 'GANDHINAGAR'), ('SHIMLA', 'SHIMLA'), ('HOSUR', 'HOSUR'), ('AMARAVATI', 'AMARAVATI'), ('GANGTOK', 'GANGTOK'), ('KOTTAYAM', 'KOTTAYAM')], max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608622944', max_length=200),
        ),
    ]
