# Generated by Django 3.0 on 2020-12-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0099_auto_20201222_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608625009', max_length=200),
        ),
    ]
