# Generated by Django 3.0 on 2020-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0104_auto_20201222_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608625764', max_length=200),
        ),
    ]
