# Generated by Django 3.0 on 2020-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0108_auto_20201222_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608629212', max_length=200),
        ),
    ]
