# Generated by Django 3.0 on 2020-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0109_auto_20201222_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608633436', max_length=200),
        ),
    ]
