# Generated by Django 3.0 on 2020-12-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0113_auto_20201226_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608945465', max_length=200),
        ),
    ]
