# Generated by Django 3.0 on 2020-12-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0116_auto_20201226_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608950319', max_length=200),
        ),
    ]
