# Generated by Django 3.0 on 2020-12-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0119_auto_20201226_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608967522', max_length=200),
        ),
    ]
