# Generated by Django 3.0 on 2020-12-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0121_auto_20201226_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1608972101', max_length=200),
        ),
    ]
