# Generated by Django 3.0 on 2021-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0122_auto_20201226_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1610871799', max_length=200),
        ),
    ]
