# Generated by Django 3.0 on 2021-01-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0123_auto_20210117_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1610938941', max_length=200),
        ),
    ]
