# Generated by Django 3.0 on 2021-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0125_auto_20210118_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1610947542', max_length=200),
        ),
    ]
