# Generated by Django 3.0 on 2021-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0126_auto_20210118_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1610948313', max_length=200),
        ),
    ]
