# Generated by Django 3.0 on 2021-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0127_auto_20210118_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1610960510', max_length=200),
        ),
    ]
