# Generated by Django 3.0 on 2021-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0130_auto_20210118_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611135935', max_length=200),
        ),
    ]
