# Generated by Django 3.0 on 2021-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0133_auto_20210120_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611137488', max_length=200),
        ),
    ]
