# Generated by Django 3.0 on 2021-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0135_auto_20210120_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611140425', max_length=200),
        ),
    ]
