# Generated by Django 3.0 on 2021-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0138_auto_20210120_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611313534', max_length=200),
        ),
    ]
