# Generated by Django 3.0 on 2021-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0140_auto_20210122_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611318738', max_length=200),
        ),
    ]
