# Generated by Django 3.0 on 2021-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0142_auto_20210122_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611416815', max_length=200),
        ),
    ]
