# Generated by Django 3.0 on 2021-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0144_auto_20210123_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611579064', max_length=200),
        ),
    ]
