# Generated by Django 3.0 on 2021-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0145_auto_20210125_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1611579336', max_length=200),
        ),
    ]
