# Generated by Django 3.0 on 2021-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0147_auto_20210126_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1632028012', max_length=200),
        ),
    ]
