# Generated by Django 3.2.4 on 2021-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0148_auto_20210919_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1635271348', max_length=200),
        ),
    ]
