# Generated by Django 3.2.4 on 2021-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0161_alter_gallery_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='timecreated',
            field=models.CharField(default='1636892148', max_length=200),
        ),
    ]
