# Generated by Django 3.2.9 on 2021-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyarea', models.CharField(max_length=122)),
                ('propertytype', models.CharField(max_length=122)),
                ('totalunits', models.CharField(max_length=122)),
                ('availaleunits', models.CharField(max_length=122)),
                ('propertylocation', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('totalfloor', models.CharField(max_length=122)),
                ('hall', models.ImageField(upload_to='media/property/hall')),
                ('kitchen', models.ImageField(upload_to='media/property/kitchen')),
                ('room', models.ImageField(upload_to='media/property/room')),
                ('bathroom', models.ImageField(upload_to='media/property/bathroom')),
                ('design', models.ImageField(upload_to='media/propertydesign')),
            ],
        ),
    ]
