# Generated by Django 3.2.9 on 2021-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyname',
            field=models.CharField(default=2, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.ImageField(upload_to='property/bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='design',
            field=models.ImageField(upload_to='property/design'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hall',
            field=models.ImageField(upload_to='property/{{propertyname}}/hall'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.ImageField(upload_to='property/kitchen'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room',
            field=models.ImageField(upload_to='property/room'),
        ),
    ]
