# Generated by Django 3.2.4 on 2021-11-17 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_interiordesign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='totalfloor',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Four_BHK',
            new_name='image10',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Tree_BHK',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Agriculture',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='NA_plot',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Villa',
            new_name='image5',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Two_BHK',
            new_name='image6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='One_BHK',
        ),
        migrations.AddField(
            model_name='property',
            name='buildername',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='cooling',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/kitchen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/bathroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='petfriendly',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='propertycondition',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='propertydescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='propertyvideo',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='swimmingpool',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='yearbuilt',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
