# Generated by Django 3.2.4 on 2021-11-28 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211117_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image10',
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property/room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(upload_to='property/room'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(upload_to='property/bathroom'),
        ),
    ]
