# Generated by Django 3.2.4 on 2021-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211128_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyarea', models.CharField(max_length=122)),
                ('propertyname', models.CharField(max_length=122)),
                ('propertytype', models.CharField(max_length=122)),
                ('totalunits', models.CharField(max_length=122)),
                ('availaleunits', models.CharField(max_length=122)),
                ('propertylocation', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('Status', models.CharField(max_length=122)),
                ('buildername', models.CharField(max_length=122)),
                ('propertydescription', models.CharField(max_length=122)),
                ('propertyvideo', models.CharField(max_length=122)),
                ('propertycondition', models.CharField(max_length=122)),
                ('yearbuilt', models.CharField(max_length=122)),
                ('petfriendly', models.CharField(max_length=122)),
                ('furnished', models.CharField(max_length=122)),
                ('cooling', models.CharField(max_length=122)),
                ('swimmingpool', models.CharField(max_length=122)),
                ('thumbnail', models.ImageField(upload_to='property/room')),
                ('image1', models.ImageField(upload_to='property/room')),
                ('image2', models.ImageField(upload_to='property/room')),
                ('image3', models.ImageField(upload_to='property/bathroom')),
                ('image4', models.ImageField(upload_to='property/bathroom')),
                ('image5', models.ImageField(upload_to='property/design')),
                ('image6', models.ImageField(upload_to='property/kitchen')),
                ('image7', models.ImageField(upload_to='property/room')),
                ('image8', models.ImageField(upload_to='property/bathroom')),
                ('image9', models.ImageField(upload_to='property/design')),
            ],
        ),
    ]
