# Generated by Django 3.0 on 2020-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200801_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='property_type',
            field=models.ManyToManyField(to='blog.Property_type'),
        ),
    ]
