# Generated by Django 3.0 on 2020-08-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200803_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property_type',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='version',
        ),
    ]
